import PySimpleGUI as sg

sg.theme('DefaultNoMoreNagging')

FONT_FAMILY = sg.DEFAULT_FONT[0]

DETECTION_STATUS_IDLE = '#0000FF'
DETECTION_STATUS_READING = '#FFFF00'
DETECTION_STATUS_SUCCESS = '#00FF00'
DETECTION_STATUS_ERROR = '#FF0000'

IMAGE_BLANK_PROFILE = r'assets/blank-profile.png'
